### ISSUE TITLE
Donations

### ISSUE THREAD

**Issue by ahadley1124** [sshine/simplex-desktop#15]
While browsing the Simplex-Chat repository, they mention the use of [Open Collaborative](https://opencollective.com/). Browsing around the Open Collaborative website shows that we can join under the [Open Source Collective](https://www.oscollective.org/) which takes a 10% fee but will handle the accounting, taxes, legal, and administration. By accepting the 10% fee, any taxes that would be due from accepting donations is taken care of by Open Collective along with legal problems that could arise with new laws coming into effect in every country. Another benefit of accepting donations is to have an audit completed when the time is right.

**Comment by sshine** [comment]
Let’s focus on getting a working prototype before we start any fundraising. I’m not convinced dragging money into this project will accelerate it.

**Comment by ahadley1124** [comment]
OK. I have started working on the websocket last night and will continue working on it tonight.

**Comment by Okkonen-GitHub** [comment]
I agree with @sshine here, if people want to donate they should donate to the official simplex project.

**Comment by Okkonen-GitHub** [comment]
> OK. I have started working on the websocket last night and will continue working on it tonight.

Great!
